# Site Settings

title: Snoopy's code cave | Testing grounds
tagline: Proceed at your own risk
keywords: github pages, single page apps

description: >
  Testing grounds for misc stuff.... now trying JavaScript and Html


# Exclude from Jekyll processing
exclude: ["Readme.md", "package.json"]
